"""add_report_status_column

Revision ID: bac7655602fc
Revises: f162f9664812
Create Date: 2026-03-31 16:32:48.696490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac7655602fc'
down_revision: Union[str, Sequence[str], None] = 'f162f9664812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add with server default so existing rows get a value
    op.add_column('reports', sa.Column('status', sa.String(length=20), nullable=False, server_default='completed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'status')
    # ### end Alembic commands ###
